### ISSUE TITLE
Felix salesteam mobile

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#18]
Remove the contact information from the header when the site switches to mobile.

Center the logo vertically and horizontally.

Fix "Shipping" Section under Documents. Aligned too far left.

Enlarge all text under 30px by 2-4 pixels. (use best judgement for headlines/links/body copy)

**Comment by travishathaway** [comment]
@loreguerra 

I fixed the header.  You can see that on the staging site.

I am confused about the other requests though.  It checked out the "Shipping" menu item, and everything appears to be aligned correctly.

Regarding the text under 30px, is this the menu text? or all the text?  Because most of the text on the site is under 30px.

**Comment by loreguerra** [comment]
See comments on #16 

Also, the logo here should be centered. You can use the logo from the staging felix site and make it look similar that site's header.

![photo apr 19 1 04 01 pm](https://cloud.githubusercontent.com/assets/16310498/14653792/7dd9ce58-062f-11e6-8613-75bdace15841.png)

**Comment by travishathaway** [comment]
@loreguerra 

It's updated on staging.  This will be included next time I update the production server.

**Comment by loreguerra** [comment]
The header looks great on staging for both.
